---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deadmanswatch
  labels:
    app.kubernetes.io/name: deadmanswatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: deadmanswatch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deadmanswatch
    spec:
      containers:
        - name: deadmanswatch
          image: "kierranm/deadmanswatch:v0.0.1"
          imagePullPolicy: IfNotPresent
          args:
            - watch
            - --port=8080
            - --listen-address=0.0.0.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {}